version: '3.9'

services:
  frontend:
    build:
      context: dockerfiles
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src/:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  vite:
    build:
      context: dockerfiles
      dockerfile: vite.Dockerfile
    volumes:
      - ./src/:/app