services:
  dev:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  vite:
    build:
      context: .
      dockerfile: ./dockerfiles/vite.Dockerfile
    volumes:
      - ./:/app
  node-runner:
    build:
      context: .
      dockerfile: ./dockerfiles/node-runner.Dockerfile
    volumes:
      - ./:/app